### ISSUE TITLE
Error when moving units.

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#14]
None
Traceback (most recent call last):
  File "client.py", line 91, in <module>
    eTypestoListeners = init()
  File "client.py", line 83, in init
    eventManager.post(Event.StartEvent())
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Manager.py", line 59, in post
    listener.notify(event)
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Window.py", line 264, in notify
    self.run()
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Window.py", line 122, in run
    self.manager.post(Event.UpdateEvent(self.gameFrametime,self.gameTime))
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Manager.py", line 59, in post
    listener.notify(event)
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Universe.py", line 47, in notify
    self.update()#this may become a thread
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Universe.py", line 38, in update
    self.activeWorld.update()
  File "/Users/julian/Complete-Galactic-Dominion/architecture/World.py", line 44, in update
    entity.update()
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Unit.py", line 40, in update
    self.move()
  File "/Users/julian/Complete-Galactic-Dominion/architecture/Unit.py", line 73, in move
    dirx=self.dest[0]-curX #unscaled x direction of movement
TypeError: 'NoneType' object is unsubscriptable

**Comment by jceipek** [comment]
Error is in statement starting on line 78 of Unit.py. Problem occurs if

```
  dest == None 
```

when 

```
  not self.status == Locals.IDLE
```

This implies that state can be something other than Locals.IDLE when there is no destination.

@jkirschner, @pvarin, @berit: people who wrote the movement/attacking code, is this a possibility that makes sense? If not, we have to find the root cause of the problem. Otherwise, we can just change line 78 of Units.py to

```
  if not self.status == Locals.IDLE and self.dest:
```
