### ISSUE TITLE
Crash while selecting units

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#23]
I haven't had time to investigate this yet.

```
    An unexpected error occurred in the event thread.
    Traceback (most recent call last):
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/Window.py", line 254, in pygameEventPoster
        self.manager.post(i) #Warning: make sure that threading doesn't cause \
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/Manager.py", line 56, in post
        listener.notify(event)
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/UserInterface.py", line 82, in notify
        self.activeScreen.processAddDragCompletedEvent(event)
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/Screen.py", line 86, in processAddDragCompletedEvent
        self.viewport.completeDrag(event)
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/Viewport.py", line 198, in completeDrag
        self.dragSelect(event)
      File "/home/jceipek/CGD/Complete-Galactic-Dominion/architecture/Viewport.py", line 236, in dragSelect
        drawRect = entity.rect.move(entity.drawOffset)
    TypeError: argument must contain two numbers
    63420775203338716 <class 'Event.QuitEvent.QuitEvent'>
        No Additional Debug Info Available
```

**Comment by pvarin** [comment]
Pretty sure I fixed this yesterday Apr 22
